### ISSUE TITLE
I made a test transaction about $10 a month ago, but there is zero on my desktop Bither wallet.

### ISSUE THREAD

**Issue by Astraport** [bither/bither-desktop-java#11]
Why and where is the money?

**Comment by bithernet** [comment]
Have you synced to the newest block?
You can look at the block syncing status in Advanced Options - Network Monitoring - Peers/Blocks

**Comment by Astraport** [comment]
![2019-06-02_17-49-15](https://user-images.githubusercontent.com/1259709/58762207-6b932d80-8556-11e9-8df4-94f7397aabbb.png)
>You can look at the block syncing status
Not find it

**Comment by Astraport** [comment]
My transaction https://www.blockchain.com/btc/address/1KyCsYk7tCxnSnk7hLBtwGm72Yg5ytwjxx

**Comment by bithernet** [comment]
More ->
Peers
Blocks

**Comment by Astraport** [comment]
I have empty fields in Peers and Blocks popups
![2019-06-06_17-45-43](https://user-images.githubusercontent.com/1259709/59037787-a52ba780-887a-11e9-9f1b-b2da7f29eee0.png)

**Comment by bithernet** [comment]
That means you cannot connect to any bitcoin nodes. Can you try other network environments? e.g. : 4G or other wifi.

**Comment by bithernet** [comment]
Also, have you ever did some actions like importing other private keys?

**Comment by ghking1** [comment]
I have the same problem, bither-andriod can work will, but bither-windows-1.4.7 can not connect to the network, they are in the same wifi.

**Comment by Astraport** [comment]
> I have the same problem, bither-andriod can work will, but bither-windows-1.4.7 can not connect to the network, they are in the same wifi.
Are they scammers?

**Comment by ghking1** [comment]
> > I have the same problem, bither-andriod can work will, but bither-windows-1.4.7 can not connect to the network, they are in the same wifi.
> > Are they scammers?

Probably not, it's open source, and recommand by some authoritative orgnization.

**Comment by ghking1** [comment]
> Also, have you ever did some actions like importing other private keys?

@bithernet   I have imported a HD acount and one private key

**Comment by songchenwen** [comment]
> I have empty fields in Peers and Blocks popups
> ![2019-06-06_17-45-43](https://user-images.githubusercontent.com/1259709/59037787-a52ba780-887a-11e9-9f1b-b2da7f29eee0.png)

It looks like Bither cannot connect to the internet. Can you provide more information like which operating system you are on, and which version of bither you use?

You may try to import the private key to your mobile device as a temporary workaround as we are looking into it. @Astraport

**Comment by songchenwen** [comment]
@Astraport @ghking1 

I've looked into this issue. [This is a problem with JVM](https://superuser.com/a/928498) which affects windows users. We will pack a new version which will probably get this issue fixed. 

In the mean time,  there is a workaround for you.

1. Find the java package of Bither on your PC. It should be in `C:\Users\{user_name}\AppData\Roaming\JWrapper-Bither\`. Replace {user_name} to your PC account user name.
2. In the Bither java package folder, find a folder begin with `JWrapper-Windows64JRE`, click into it, in the `bin` folder you can find `java.exe`.
3.  In the Bither java package folder, find a folder begin with `JWrapper-Bither`, in this folder you can find `bither-desktop-1.4.7.jar` 
4. Open `cmd` and combine the path of `java.exe` and `bither-desktop-1.4.7.jar` with some extra options `-Dhttps.protocols=TLSv1.1,TLSv1.2 -jar` to build a command that looks like this `C:\Users\{user_name}\AppData\Roaming\JWrapper-Bither\JWrapper-Windows64JRE-{some_digits}-complete\bin\java.exe -Dhttps.protocols=TLSv1.1,TLSv1.2 -jar C:\Users\scw\AppData\Roaming\JWrapper-Bither\JWrapper-Bither-{some_digits}-complete\bither-desktop-1.4.7.jar`
5. Type `enter` to let it run. Head into More -> Peers. Now you should see some connected peers.

**Comment by Astraport** [comment]
@songchenwen Although I have an old version bither-desktop-1.4.5.jar, everything worked! 
I can see the blocks now.
However, my balance is still $0

**Comment by songchenwen** [comment]
> @songchenwen Although I have an old version bither-desktop-1.4.5.jar, everything worked!
> I can see the blocks now.
> However, my balance is still $0

You need to wait until the max block number is higher than your transaction’s confirmation block number to see your balance.

**Comment by songchenwen** [comment]
Hi @Astraport . Do you have your balance now?

**Comment by Astraport** [comment]
Hi @songchenwen ! The same
![2020-02-04_09-18-24](https://user-images.githubusercontent.com/1259709/73716075-10d65500-4727-11ea-8eef-cb4cad2eb8f4.png)

My transaction https://www.blockchain.com/btc/address/1KyCsYk7tCxnSnk7hLBtwGm72Yg5ytwjxx

**Comment by songchenwen** [comment]
@Astraport you can try these steps to see if you can get your balance right.

1. Update to the latest version.
2. Start Bither with the workaround above.
3. More -> Advanced Options -> Reload Transactions data

Please let me know if you have any result.

**Comment by Astraport** [comment]
Awesome! All work after update! Many thanks @songchenwen

**Comment by songchenwen** [comment]
Hi @Astraport , a new version of Bither Desktop is released. We've fixed the TLS issue. You can launch Bither Desktop as usual now.

**Comment by ghking1** [comment]
> Hi @Astraport , a new version of Bither Desktop is released. We've fixed the TLS issue. You can launch Bither Desktop as usual now.

me too, may the author can publish a new version to resolve this problem, thanks!

**Comment by ghking1** [comment]
Thank you for your effort very much! It can really work now.
