### ISSUE TITLE
how to withdrawl Amount From Bither Hot Wallet

### ISSUE THREAD

**Issue by Bhagatmonu** [bither/bither-desktop-java#12]
I have 100 Bitcoin In My Bither Wallet i Think i Lost My All Coin Becoz I am Unable to withdrawal or exchange Bitcoin 
If anyone Help Me to withdrawal These Bitcoin i will Share My Bither With Him/her

Hope Someone Help me Soon

**Comment by Frankonsite** [comment]
Talk to Onsite Control on the [Live help website] (https://onsitecontrol.online/) so that your problem can be investigated. To get a quicker response, kindly use the live chat icon on the lower right side to start a chat with a member of our service.

**Comment by songchenwen** [comment]
onsitecontrol has nothing to do with us. watch out for scams when you reach out for help on the internet.

**Comment by Cryptolord123** [comment]
> I have 100 Bitcoin In My Bither Wallet i Think i Lost My All Coin Becoz I am Unable to withdrawal or exchange Bitcoin If anyone Help Me to withdrawal These Bitcoin i will Share My Bither With Him/her
> 
> Hope Someone Help me Soon

Same thing happened to me but thanks to Blackhathacker111 who helped me message him on telegram his telegram username is https://t.me/Blackhathacker111

**Comment by songchenwen** [comment]
This issue is closed because it has become a scammer attractor.
