### ISSUE TITLE
初次使用bither生成 HD 账户后无法再次生成或者导入其他 HD 账户

### ISSUE THREAD

**Issue by qyvlik** [bither/bither-desktop-java#5]
# 初次使用bither生成 HD 账户后无法再次生成或者导入其他 HD 账户

由于有多个 HD 账户，故希望 bither 开发出管理多个 HD 账户的功能，由于 bither 没有提供移除当前 HD 账户的功能，所以在初次导入 HD 账户后，就会出现想更换 HD 账户，却有无能为力，毕竟多数用户都是小白，不知道如何删除 bither 账户的数据。。。

**Comment by bithernet** [comment]
未来会考虑
